#!/bin/bash

[ -f "$HOME"/.config/sys/all-env ] && . "$HOME"/.config/sys/all-env

TOUCHPAD=${TOUCHPAD:-"pointer-1267-91-Elan_Touchpad"}
# Spawn keymaps (spawns windows or execute commands)

riverctl map normal Super R spawn "$HOME/.config/river/init -s"
riverctl map normal Super+Shift R spawn "$HOME/.config/river/init"
riverctl map normal Super+Shift Return spawn foot

riverctl map normal Super+Shift E spawn "$HOME/binaries/bin/session-ctrl"
riverctl map normal Control+Alt L spawn "$HOME/binaries/bin/lock"
riverctl map normal Control+Shift+Alt Delete spawn "$HOME/binaries/bin/ly-logout"

riverctl map normal Super D spawn "$HOME/binaries/bin/menu-run"
riverctl map normal Super V spawn "$HOME/binaries/bin/clipboard"
riverctl map normal Super Period spawn "$HOME/binaries/bin/emoji"
riverctl map normal Super N spawn "networkmanager_dmenu"

riverctl map normal Super+Shift Print spawn "$HOME/binaries/bin/screenshot"
riverctl map normal Super Print spawn "$HOME/binaries/bin/screenshot -fo"
riverctl map normal Super+Control Print spawn "$HOME/binaries/bin/screenshot -so"

riverctl map -repeat normal Super+Alt H move left 10
riverctl map -repeat normal Super+Alt L move right 10
riverctl map -repeat normal Super+Alt J move down 10
riverctl map -repeat normal Super+Alt K move up 10
riverctl map normal Super+Shift+Alt H snap left
riverctl map normal Super+Shift+Alt L snap right
riverctl map normal Super+Shift+Alt J snap down
riverctl map normal Super+Shift+Alt K snap up
riverctl map -repeat normal Super+Control+Alt H resize horizontal -10
riverctl map -repeat normal Super+Control+Alt L resize horizontal 10
riverctl map -repeat normal Super+Control+Alt J resize vertical -10
riverctl map -repeat normal Super+Control+Alt K resize vertical 10


riverctl map normal Super Q close
riverctl map normal Super Return zoom

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Space focus-output next

riverctl map normal Super+Shift Space send-to-output next

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
for mode in normal locked
do
    riverctl map $mode None XF86Eject spawn "eject -T"

    riverctl map $mode None XF86AudioRaiseVolume  spawn "$HOME/binaries/bin/volume up"
    riverctl map $mode None XF86AudioLowerVolume  spawn "$HOME/binaries/bin/volume down"
    riverctl map $mode None XF86AudioMute         spawn "$HOME/binaries/bin/volume mute"
    riverctl map $mode None XF86AudioMicMute         spawn "pactl set-source-mute 0 toggle"

    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay  spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev  spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext  spawn "playerctl next"

    riverctl map $mode None XF86MonBrightnessUp   spawn "$HOME/binaries/bin/brightness up"
    riverctl map $mode None XF86MonBrightnessDown   spawn "$HOME/binaries/bin/brightness down"

    riverctl map $mode None XF86TouchpadOff spawn "$HOME/binaries/bin/tpad off"
    riverctl map $mode None XF86TouchpadOn spawn "$HOME/binaries/bin/tpad on"
done

