# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#cccaca"          # Main text color
theme[title]="#cccaca"            # Title color for boxes
theme[hi_fg]="#586268"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#8e8d8d"       # Color of inactive/disabled text
theme[graph_text]="#7F7F80"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#0D0E10"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#717071"       # Background color of selected item in processes box
theme[selected_fg]="#cccaca"       # Foreground color of selected item in processes box
theme[proc_misc]="#7F7F80"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#586268"           # Cpu box outline color
theme[mem_box]="#454E54"           # Memory/disks box outline color
theme[net_box]="#586268"           # Net up/down box outline color
theme[proc_box]="#454E54"          # Processes box outline color
theme[div_line]="#454E54"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#8e8d8d"          # Background color of the percentage meters
theme[used_start]="#7F7F80"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#7F7F80"
theme[available_start]="#8E8D8E"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#8E8D8E"
theme[cached_start]="#7F7F80"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#7F7F80"
theme[free_start]="#8E8D8E"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#8E8D8E"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#586268"        # CPU graph colors
theme[cpu_mid]="#515B62"
theme[cpu_end]="#454E54"
theme[download_start]="#7F7F80"    # Download graph colors
theme[download_mid]="#454E54"
theme[download_end]="#454E54"  
theme[upload_start]="#515B62"     # Upload graph colors
theme[upload_mid]="#515B62"
theme[upload_end]="#8E8D8E"
theme[process_start]="#7F7F80"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#8E8D8E"
theme[process_end]="#707172"