# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#ceccc9"          # Main text color
theme[title]="#ceccc9"            # Title color for boxes
theme[hi_fg]="#7C8079"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#908e8c"       # Color of inactive/disabled text
theme[graph_text]="#7A8584"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#101212"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#636660"       # Background color of selected item in processes box
theme[selected_fg]="#ceccc9"       # Foreground color of selected item in processes box
theme[proc_misc]="#7A8584"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#7C8079"           # Cpu box outline color
theme[mem_box]="#5D6460"           # Memory/disks box outline color
theme[net_box]="#7C8079"           # Net up/down box outline color
theme[proc_box]="#5D6460"          # Processes box outline color
theme[div_line]="#5D6460"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#908e8c"          # Background color of the percentage meters
theme[used_start]="#7A8584"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#7A8584"
theme[available_start]="#8F938E"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#8F938E"
theme[cached_start]="#7A8584"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#7A8584"
theme[free_start]="#8F938E"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#8F938E"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#7C8079"        # CPU graph colors
theme[cpu_mid]="#6D746F"
theme[cpu_end]="#5D6460"
theme[download_start]="#7A8584"    # Download graph colors
theme[download_mid]="#5D6460"
theme[download_end]="#5D6460"  
theme[upload_start]="#6D746F"     # Upload graph colors
theme[upload_mid]="#6D746F"
theme[upload_end]="#8F938E"
theme[process_start]="#7A8584"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#8F938E"
theme[process_end]="#86857B"