#!/bin/bash
hash bemenu 2>/dev/null || exit
hash cliphist 2>/dev/null || exit
pgrep -x bemenu && killall bemenu
# making sure all binaries are refreshed
[ -f $HOME/.config/shell/variables ] && . $HOME/.config/shell/variables
[ -f $HOME/.config/shell/path ] && . $HOME/.config/shell/path
# This to set bemenu colors
background='#1a1a1a'
color5='#268bd2'
[ -f "$HOME/.cache/wal/colors.sh" ] && . $HOME/.cache/wal/colors.sh
background=${background}ee


export BEMENU_ARGS=(-b -c -l 10 -W .3 -i -p '' --ifne --tb "$background" --tf "$color5" --fb "$background" --nb "$background" --hb "$background" --hf "$color5" "$@" --fn "JetBrains Mono NF 12")

# cliphist list | bemenu "${BEMENU_ARGS[@]}" | cliphist decode | wl-copy
cliphist list | bemenu "${BEMENU_ARGS[@]}" | cliphist decode | wl-copy
