#!/bin/bash

[ -f "$HOME"/.config/sys/all-env ] && . "$HOME/.config/sys/all-env"

hash swayidle 2>/dev/null || exit 0
hash swaylock 2>/dev/null || exit 0
pgrep -x swayidle &>/dev/null && killall swayidle &>/dev/null
pgrep -x swaylock &>/dev/null && killall swaylock &>/dev/null

LOCK_TIME=${LOCK_TIME:-50}
SUSPEND_TIME=${SUSPEND_TIME:-50}
SUSPEND_TIME=$((SUSPEND_TIME + LOCK_TIME))

lock="swaylock -f"
suspend="systemctl suspend"
[ -f "$HOME/binaries/bin/lock" ] && lock="$HOME/binaries/bin/lock"
[ -f "$HOME/binaries/bin/suspend" ] && suspend="$HOME/binaries/bin/suspend"

swayidle -w \
before-sleep "$lock" \
lock "$lock" \
timeout $LOCK_TIME 'loginctl lock-session' \
timeout $SUSPEND_TIME "$suspend" &>/dev/null &

